# -*- coding: utf-8 -*-
"""Contains Duplicate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzjQ_Z4ux3PkA_7CW1bvuZ0sa1SEWPKy
"""

class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
        heap={}
        for i in nums:
            if i in heap:
                return True
            else:
                heap[i]=1
        return False